name: Check a blocklist
description: Get a report on a blocklist.
title: Check blocklist
labels: ["check blocklist"]
body:
  - type: input
    attributes:
      label: Enter the URL of the blocklist's raw file
      description: Please allow a few minutes for the report to generate.
      placeholder: https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/wildcard_domains/scams.txt
    validations:
      required: true
