name: Check a blocklist
description: Generate a new report for a blocklist.
title: Check blocklist
labels: ["check blocklist"]
body:
  - type: input
    attributes:
      label: "Report for:"
      description: Please enter the URL to the raw file of the blocklist.
      placeholder: https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/wildcard_domains/scams.txt
    validations:
      required: true
