name: Check blocklist
on:
  issues:
    types:
      - labeled
permissions:
  contents: write
  issues: write

jobs:
  check-blocklist:
    if: $(echo ${{ github.event.label.name == 'check blocklist' }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check blocklist from issue
        run: |
          bash scripts/check.sh '$(echo ${{ github.event.issue.body }})'
          echo "$ENTRIES_BEFORE" >> $GITHUB_ENV
          echo "$LINES_REMOVED" >> $GITHUB_ENV
          echo "$ENTRIES_AFTER" >> $GITHUB_ENV
          echo "$IN_TRANCO" >> $GITHUB_ENV
          echo "$DEAD_COUNT" >> $GITHUB_ENV

      - name: Comment results
        run: |
          gh issue comment ${{ github.event.issue.number }} -b \
          $(echo ${{ env.ENTRIES_BEFORE }})
          $(echo ${{ env.LINES_REMOVED }})
          $(echo ${{ env.ENTRIES_AFTER }})
          $(echo ${{ env.IN_TRANCO }})
          $(echo ${{ env.DEAD_COUNT }})
        env:
          GH_TOKEN: $(echo ${{ github.token }})
