name: Check blocklist
on:
  issues:
    types:
      - labeled
permissions:
  contents: write
  issues: write

jobs:
  check-blocklist:
    if: ${{ github.event.label.name == 'check blocklist' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check blocklist from issue
        run: |
          bash scripts/check.sh '${{ github.event.issue.body }}'
          echo "$ENTRIES_BEFORE" >> $GITHUB_ENV
          echo "$LINES_REMOVED" >> $GITHUB_ENV
          echo "$ENTRIES_AFTER" >> $GITHUB_ENV
          echo "$IN_TRANCO" >> $GITHUB_ENV
          echo "$DEAD_COUNT" >> $GITHUB_ENV

      - name: Comment results
        run: |
          gh issue comment ${{ github.event.issue.number }} -b \
          "$(cat << EOF
          ${{ env.ENTRIES_BEFORE }}
          ${{ env.LINES_REMOVED }}
          ${{ env.ENTRIES_AFTER }}
          ${{ env.IN_TRANCO }}
          ${{ env.DEAD_COUNT }}
          EOF
          )"
        env:
          GH_TOKEN: ${{ github.token }}
