name: Test
on:
  workflow_dispatch:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install depedencies
        run: |
          time npm install -g @adguard/dead-domains-linter

      - name: Cache depedencies
        uses: actions/cache@v4
        with:
          path: |
            /usr/lib/node_modules
          key: dependencies

  test-cache:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Cache depedencies
        uses: actions/cache@v4
        with:
          path: |
            /usr/lib/node_modules
          key: dependencies

      - name: Install depedencies
        run: |
          time npm install -g @adguard/dead-domains-linter
          command -v dead-domains-linter
