name: Test
on:
  workflow_dispatch:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install depedencies
        run: |
          time npm install -g @adguard/dead-domains-linter
          time npm install -g @adguard/hostlist-compiler@1.0.23

      - name: Cache depedencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: dependencies

  test-cache:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Cache depedencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: dependencies

      - name: Install depedencies
        run: |
          time npm install -g @adguard/dead-domains-linter
          time npm install -g @adguard/hostlist-compiler
          command -v dead-domains-linter
          command -v hostlist-compiler
