name: Test
on:
  workflow_dispatch:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install depedencies
        run: |
          npm install -g @adguard/dead-domains-linter
          whereis dead-domains-linter

      - name: Cache depedencies
        uses: actions/cache@v3
        with:
          path: |
            /usr/lib/node_modules
            /usr/local/bin/dead-domains-linter
          key: dependencies

  test-cache:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Cache depedencies
        uses: actions/cache@v3
        with:
          path: |
            /usr/lib/node_modules
            /usr/local/bin/dead-domains-linter
          key: dependencies

      - name: Verify dependencies were installed
        run: dead-domains-linter
